### PR TITLE
added scaling (pinch) functionality

### PR DESCRIPTION
**Pull request by SebastianAT**
For Android i have added pinchgesture functionality in order to be able to scale the model. Only problem i did not found to set a limit on max or min scale.
[AndroidARView.zip](https://github.com/CariusLars/ar_flutter_plugin/files/8949321/AndroidARView.zip)
[libs.zip](https://github.com/CariusLars/ar_flutter_plugin/files/8949328/libs.zip)

### CODE REVIEW

**Comment by SebastianAT** [comment]
Solved: Also added minScale (0.1f) and maxScale (10.0f)
[ArModelBuilder.zip](https://github.com/CariusLars/ar_flutter_plugin/files/8950418/ArModelBuilder.zip)
e

**Comment by CariusLars** [comment]
Hey @SebastianAT, as far as I can see there are no code changes? Haven´t had the chance to look into the files you attached yet but could you explain why there are no commits form you in this PR? Sorry for the confusion and really appreciate that you are contributing to this plugin :)

**Comment by SebastianAT** [comment]
Hey unfortunately i could not Upload kotlin files directly so i had to put
the files in zip files and then i uploaded it. Maybe it does not recognize
those files.
But they are attached, please verify this manually.

Can you tell me how i can achivie to use Material color change of a local
GLTF file?

Chees
Sebastian

Lars Carius ***@***.***> schrieb am So., 26. Juni 2022, 20:43:

**Comment by CariusLars** [comment]
Unfortunately it's almost impossible to review like this because I can't see the diffs... Why did committing and pushing the kotlin files not work? what's the output of `git status` after the changes you applied?

**Comment by SebastianAT** [comment]
image

as you see on the image github does not allow me to upload kotlin files ... idk why... i did not copy the whole repo i just wanted to upload by the webpage github provides. 

To see the difference just take the old file and the new file and check on this site: https://www.diffchecker.com/ and now you will be able to see the differences.

If you were not able i will try another workaround and download the whole repo and push it back with the state of me.

**Pull request closed without merging**
