### PR TITLE
Add support to calculate distance between device and anchor and distance between two anchors

### PR DESCRIPTION
**Pull request by dnkoulouris**
This pull request implements two functionalities that are required for many use cases:
- calculate distance from device to anchor
- calculate distance between two anchors  

The distance is counted in meters and uses the Vector 3 square root method.  
Method `getCameraPose()` that obtains device coordinates is required and was cloned from gps branch

Methods added in `ar_session_manager.dart` along with the required platform code in Swift and Kotlin: 
- `getPose(ARAnchor anchor)`: Returns the given anchor pose in Matrix4 format with respect to the world coordinate system of the ARView.
- `getDistanceBetweenAnchors(ARAnchor anchor1, ARAnchor anchor2)`: Returns the distance in meters between @anchor1 and @anchor2.
- `getDistanceFromAnchor(ARAnchor anchor)`: Returns the distance in meters between @anchor and device's camera.
- `getDistanceBetweenVectors(Vector3 vector1, Vector3 vector2)`: Returns the distance in meters between @vector1 and @vector2.

### CODE REVIEW

**Comment by Petroni** [comment]
Tested out getDistanceFromAnchor and getDistanceBetweenAnchors on iOS and all seems to be working well without any issues. Currently in the process of testing on Android

**Comment by CariusLars** [comment]
Hey @dnkoulouris , thanks for the contribution! I left a few comments on your code but looks good otherwise, once @Petroni is done testing on Android and the comments are fixed I'm happy to merge :)

**Comment by Petroni** [comment]
2 Small issues on the Android side. AndroidARView.kt f line 108 & 116 are throwing errors due to being passing null values. 
Managed to fix this from my end by passing an empty string instead of null.

**Comment by dnkoulouris** [comment]
So, what is the current status?

**Comment by dnkoulouris** [comment]
I also fixed the error that @Petroni mentioned in my fork

**Comment by CariusLars** [comment]
Hey folks, sorry for the late reply, I've been very busy the last couple of weeks..

@dnkoulouris thanks for the fix, could you reply to / fix the three review comments I left after your initial PR above? After that I´m happy to merge :)

**Comment by CariusLars** [comment]
if you scroll up on this page you should see three review comments (they are not commits). I'v attached a screenshot below 
image

**Comment by dnkoulouris** [comment]
Readme file reverted to the original state.  
Concerning the Info.plist issue, according to this:
[https://github.com/flutter/flutter/issues/94508 ](https://github.com/flutter/flutter/issues/94508)
I added the flag to support higher frame rates in iPhone screens (iPhone 13 series).

**Comment by CariusLars** [comment]
awesome, thanks @dnkoulouris! I merged this just now :)

**Pull request merged**
