### PR TITLE
fix: session was not closed issue in Android

### PR DESCRIPTION
**Pull request by Koobonik**
Hi Guys,
I fixed error in Android!

In version 0.6.0, the app turned off after 30 times dispose.
In version 0.6.1, the app turned off after 70 times dispose.
And now, The app does not turn off after dispose!
The animation continued to be soft and the amount of heat generated became very low.
Overall, it was optimized.

### CODE REVIEW

**Comment by CariusLars** [comment]
nice! I'll have a look at the new code this afternoon or at the latest this weekend and merge it into main :)

**Comment by CariusLars** [comment]
@Koobonik I left a few questions in your code, after they are clarified I'll merge it :)

**Comment by Koobonik** [comment]
> @Koobonik I left a few questions in your code, after they are clarified I'll merge it :)

I always feel grateful for your efforts.

**Comment by CariusLars** [comment]
hey @Koobonik , can you have a look at the questions I asked on this PR? if we clarify this I can go on and merge it :)

**Comment by Koobonik** [comment]
@CariusLars Yes, You can.
How can I see your questions?

**Comment by CariusLars** [comment]
they are further up in this discussion thread, I've attached a screenshot on how it looks for me:
image

**Comment by Koobonik** [comment]
In the fisrt case, So many flutter libs set null after dispose. because, It helps to prevent memory leak.

second case, you right, The difference from arcore was compared. I think I made a mistake there. you can delete "faceSceneUpdateListener" function

**Comment by CariusLars** [comment]
are you sure the method call handlers are automatically disposed?

also, could you remove the faceSceneUpdateListener code pieces so I can compare and test the code better?

Thanks @Koobonik !

**Comment by Koobonik** [comment]
hi @CariusLars 
sorry about too late
I will send a new code in Sunday. :)

**Comment by naveenbharadwaj19** [comment]
@Koobonik Any update #71 ? Am i the only one facing this issue ?

**Comment by Koobonik** [comment]
@naveenbharadwaj19 
Does it mean an issue that Turn OFF when you go home while running the app and then return right?

**Comment by naveenbharadwaj19** [comment]
@Koobonik Well yeah. It's terminating whole app . I've added a demo video in #71 how the crash is happening

**Comment by CariusLars** [comment]
@Koobonik I've merged your changes into main in the current v0.6.2

**Comment by Koobonik** [comment]
@CariusLars Thanks! If I find something. I will PR :)

**Pull request closed without merging**
