### PR TITLE
fix some bugs

### PR DESCRIPTION
**Pull request by Koobonik**
Hi guys,

I found some error or some bug

1. This prevents the app from turning off when other errors occur in addition to errors occurring in the camera. (There's nothing bad about this.)

2. I think the 'addNode' function should return true only when the node is well placed.
Therefore, I wrote the code to return false otherwise.

### CODE REVIEW

**Comment by CariusLars** [comment]
hey @Koobonik I completely missed this one, sorry! Is this still up-to-date? In that case I will merge it 👍

**Comment by Koobonik** [comment]
Sure! You can merge it now !

**Comment by CariusLars** [comment]
awesome! Could you write an entry for your fixes into `changelog.md` (just use v0.6.3) and also set this version number in the, readme and the  `pubspec.yaml`? I can then just merge and publish the fixed version to the flutter store :) 

Thanks for your contribution!

**Comment by Koobonik** [comment]
Hi @CariusLars  !
I did your request! Thank you for accept my commit :)

**Review by CariusLars — APPROVED** [review]

**Pull request merged**
